In [1]:
import pandas as pd

df = pd.read_csv("sales_large.csv")

In [2]:
df[["Product", "Price"]]

       Product  Price
0       Laptop  50000
1        Phone  20000
2        Table   7000
3        Chair   1500
4   Headphones   2000
5       Laptop  55000
6         Sofa  20000
7        Phone  22000
8        Chair   1800
9        Table   7500
10      Laptop  52000
11  Headphones   2500
12       Phone  21000
13        Sofa  18000
14       Chair   1700
15      Laptop  53000
16       Table   8000
17       Phone  23000
18  Headphones   1800
19        Sofa  21000
20      Laptop  51000
21       Chair   1600
22       Phone  19000
23       Table   7800
24  Headphones   2200
25        Sofa  20000
26      Laptop  54000
27       Phone  24000
28       Chair   1500
29       Table   7600
30  Headphones   2100
31      Laptop  56000
32       Phone  20500
33       Chair   1400
34        Sofa  19500
35       Table   8200
36  Headphones   1900
37      Laptop  57000
38       Phone  22500
39       Chair   1600
40        Sofa  22000
41       Table   7900
42  Headphones   2000
43      Laptop  58000
44       Phone  21500
45       Chair   1500
46        Sofa  20500
47       Table   8300
48  Headphones   2100
49      Laptop  59000

In [3]:
df[df["Price"] > df["Price"].mean()]

    OrderID Customer Region Product     Category  Quantity  Price   OrderDate
0      1001    Afeef  South  Laptop  Electronics         1  50000  2024-01-10
1      1002    Rahul  North   Phone  Electronics         2  20000  2024-01-12
5      1006     Ravi  North  Laptop  Electronics         1  55000  2024-01-22
6      1007     Neha   West    Sofa    Furniture         1  20000  2024-01-25
7      1008      Ali   East   Phone  Electronics         2  22000  2024-01-28
10     1011     Aman   West  Laptop  Electronics         1  52000  2024-02-07
12     1013    Kiran  South   Phone  Electronics         1  21000  2024-02-12
15     1016   Sameer   East  Laptop  Electronics         1  53000  2024-02-20
17     1018     Manu  North   Phone  Electronics         1  23000  2024-02-25
19     1020    Sneha   East    Sofa    Furniture         1  21000  2024-03-02
20     1021    Akhil  South  Laptop  Electronics         1  51000  2024-03-05
25     1026     Ajay  North    Sofa    Furniture         1  20000  2024-03-18
26     1027    Latha   West  Laptop  Electronics         1  54000  2024-03-20
27     1028    Imran   East   Phone  Electronics         2  24000  2024-03-22
31     1032     Arif   East  Laptop  Electronics         1  56000  2024-04-04
32     1033    Kavya  South   Phone  Electronics         2  20500  2024-04-06
34     1035    Anita   West    Sofa    Furniture         1  19500  2024-04-10
37     1038    Priya  North  Laptop  Electronics         1  57000  2024-04-18
38     1039  Karthik   West   Phone  Electronics         2  22500  2024-04-20
40     1041     Asha  South    Sofa    Furniture         1  22000  2024-04-25
43     1044     Omar   East  Laptop  Electronics         1  58000  2024-05-03
44     1045     Tina  South   Phone  Electronics         2  21500  2024-05-05
46     1047     Maya   West    Sofa    Furniture         1  20500  2024-05-10
49     1050     Ritu  North  Laptop  Electronics         1  59000  2024-05-18

In [4]:
df.sort_values("Price", ascending=False)

,OrderID,Customer,Region,Product,Category,Quantity,Price,OrderDate
49,1050,Ritu,North,Laptop,Electronics,1,59000,2024-05-18
43,1044,Omar,East,Laptop,Electronics,1,58000,2024-05-03
37,1038,Priya,North,Laptop,Electronics,1,57000,2024-04-18
31,1032,Arif,East,Laptop,Electronics,1,56000,2024-04-04
5,1006,Ravi,North,Laptop,Electronics,1,55000,2024-01-22
26,1027,Latha,West,Laptop,Electronics,1,54000,2024-03-20
15,1016,Sameer,East,Laptop,Electronics,1,53000,2024-02-20
10,1011,Aman,West,Laptop,Electronics,1,52000,2024-02-07
20,1021,Akhil,South,Laptop,Electronics,1,51000,2024-03-05
0,1001,Afeef,South,Laptop,Electronics,1,50000,2024-01-10
27,1028,Imran,East,Phone,Electronics,2,24000,2024-03-22
17,1018,Manu,North,Phone,Electronics,1,23000,2024-02-25
38,1039,Karthik,West,Phone,Electronics,2,22500,2024-04-20
40,1041,Asha,South,Sofa,Furniture,1,22000,2024-04-25
7,1008,Ali,East,Phone,Electronics,2,22000,2024-01-28
44,1045,Tina,South,Phone,Electronics,2,21500,2024-05-05
12,1013,Kiran,South,Phone,Electronics,1,21000,2024-02-12
19,1020,Sneha,East,Sofa,Furniture,1,21000,2024-03-02
46,1047,Maya,West,Sofa,Furniture,1,20500,2024-05-10
32,1033,Kavya,South,Phone,Electronics,2,20500,2024-04-06
25,1026,Ajay,North,Sofa,Furniture,1,20000,2024-03-18
6,1007,Neha,West,Sofa,Furniture,1,20000,2024-01-25
1,1002,Rahul,North,Phone,Electronics,2,20000,2024-01-12
34,1035,Anita,West,Sofa,Furniture,1,19500,2024-04-10
22,1023,Rohan,West,Phone,Electronics,3,19000,2024-03-10
13,1014,Arun,North,Sofa,Furniture,1,18000,2024-02-15
47,1048,Noor,East,Table,Furniture,2,8300,2024-05-12
35,1036,Salim,East,Table,Furniture,2,8200,2024-04-12
16,1017,Pooja,South,Table,Furniture,2,8000,2024-02-23
41,1042,Raj,North,Table,Furniture,1,7900,2024-04-28
23,1024,Nisha,East,Table,Furniture,1,7800,2024-03-12
29,1030,Suresh,North,Table,Furniture,1,7600,2024-03-28
9,1010,Vinay,North,Table,Furniture,1,7500,2024-02-05
2,1003,Meena,West,Table,Furniture,1,7000,2024-01-15
11,1012,Riya,East,Headphones,Electronics,2,2500,2024-02-10
24,1025,Vimal,South,Headphones,Electronics,2,2200,2024-03-15
30,1031,Farah,West,Headphones,Electronics,3,2100,2024-04-01
48,1049,Amit,South,Headphones,Electronics,3,2100,2024-05-15
4,1005,Anu,South,Headphones,Electronics,3,2000,2024-01-20
42,1043,Zara,West,Headphones,Electronics,3,2000,2024-05-01
36,1037,Mehul,South,Headphones,Electronics,5,1900,2024-04-15
18,1019,Anil,West,Headphones,Electronics,4,1800,2024-02-28
8,1009,Sara,South,Chair,Furniture,2,1800,2024-02-01
14,1015,Divya,West,Chair,Furniture,3,1700,2024-02-18
21,1022,Deepa,North,Chair,Furniture,2,1600,2024-03-08
39,1040,Sunil,East,Chair,Furniture,2,1600,2024-04-22
45,1046,Dev,North,Chair,Furniture,4,1500,2024-05-08
28,1029,Keerthi,South,Chair,Furniture,4,1500,2024-03-25
3,1004,John,East,Chair,Furniture,4,1500,2024-01-18
33,1034,Ramesh,North,Chair,Furniture,3,1400,2024-04-08

In [5]:
df[(df["Region"] == "South") & (df["Price"] > 20000)]

    OrderID Customer Region Product     Category  Quantity  Price   OrderDate
0      1001    Afeef  South  Laptop  Electronics         1  50000  2024-01-10
12     1013    Kiran  South   Phone  Electronics         1  21000  2024-02-12
20     1021    Akhil  South  Laptop  Electronics         1  51000  2024-03-05
32     1033    Kavya  South   Phone  Electronics         2  20500  2024-04-06
40     1041     Asha  South    Sofa    Furniture         1  22000  2024-04-25
44     1045     Tina  South   Phone  Electronics         2  21500  2024-05-05