In [41]:
import pandas as pd

df = pd.read_csv("Messy_Sales_Data.csv")

df.head()

,Order ID,Customer Name,Product,Category,Order Date,Quantity,Unit Price,Total Amount,City,Payment Method
0,1001.0,John Doe,Laptop,Electronics,01-01-2024,1,750,750.0,New York,Credit Card
1,1002.0,Jane Smith,Smartphone,Electronics,02/01/2024,2,500,1000.0,Los Angeles,Debit Card
2,1003.0,Rahul Kumar,Headphones,Electronics,03-01-2024,3,50,150.0,Mumbai,Cash
3,1004.0,Emily Davis,Office Chair,Furniture,04-01-2024,1,120,120.0,London,Credit Card
4,1005.0,Ahmed Ali,Desk,Furniture,05-01-2024,2,200,400.0,Dubai,Online Payment

In [42]:
df.isnull().sum()

Order ID          1
Customer Name     1
Product           0
Category          0
Order Date        0
Quantity          1
Unit Price        0
Total Amount      1
City              0
Payment Method    0
dtype: int64

In [44]:
df = df.dropna(subset=["Order ID"])

df.isnull().sum()

Order ID          0
Customer Name     1
Product           0
Category          0
Order Date        0
Quantity          1
Unit Price        0
Total Amount      1
City              0
Payment Method    0
dtype: int64

In [58]:
df["Customer Name"] = df["Customer Name"].fillna("Unknown")

In [59]:
df.isnull().sum()

Order ID          0
Customer Name     0
Product           0
Category          0
Order Date        0
Quantity          1
Unit Price        0
Total Amount      1
City              0
Payment Method    0
dtype: int64

In [61]:
df = df.drop_duplicates()

df.shape

(23, 10)

In [80]:
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")
df["Unit Price"] = pd.to_numeric(df["Unit Price"], errors="coerce")

In [82]:
df["Quantity"] = df["Quantity"].fillna(df["Total Amount"]/df["Unit Price"])

In [85]:
df["Unit Price"] = df["Unit Price"].fillna(df["Total Amount"]/df["Quantity"])

In [86]:
df["Total Amount"] = df["Total Amount"].fillna(df["Quantity"] * df["Unit Price"])

In [87]:
df.isnull().sum()

Order ID          0
Customer Name     0
Product           0
Category          0
Order Date        0
Quantity          0
Unit Price        0
Total Amount      0
City              0
Payment Method    0
dtype: int64

In [89]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 23 entries, 0 to 23
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        23 non-null     float64
 1   Customer Name   23 non-null     object
 2   Product         23 non-null     object
 3   Category        23 non-null     object
 4   Order Date      23 non-null     object
 5   Quantity        23 non-null     float64
 6   Unit Price      23 non-null     float64
 7   Total Amount    23 non-null     float64
 8   City            23 non-null     object
 9   Payment Method  23 non-null     object
dtypes: float64(4), object(6)
memory usage: 2.0+ KB

,Order ID,Customer Name,Product,Category,Order Date,Quantity,Unit Price,Total Amount,City,Payment Method
0,1001.0,John Doe,Laptop,Electronics,01-01-2024,1.0,750.0,750.0,New York,Credit Card
1,1002.0,Jane Smith,Smartphone,Electronics,02/01/2024,2.0,500.0,1000.0,Los Angeles,Debit Card
2,1003.0,Rahul Kumar,Headphones,Electronics,03-01-2024,3.0,50.0,150.0,Mumbai,Cash
3,1004.0,Emily Davis,Office Chair,Furniture,04-01-2024,1.0,120.0,120.0,London,Credit Card
4,1005.0,Ahmed Ali,Desk,Furniture,05-01-2024,2.0,200.0,400.0,Dubai,Online Payment

In [90]:
df.to_csv("cleaned_sales_data.csv", index=False)